source 'http://gems.ruby-china.org'
#ruby '2.2.3'
gem 'rails', '4.2.7.1'
gem 'ruby-oci8','~> 2.2.0.2'
gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
gem 'composite_primary_keys', '~> 8.1', '>= 8.1.3'
gem 'ruby-plsql'
gem 'uuid', '~> 2.3', '>= 2.3.8'
gem 'devise'
gem 'devise_ldap_authenticatable'
gem 'haml-rails'
gem 'simple_form'
gem 'paperclip', '~> 4.3.0'
gem 'kaminari'
gem 'tzinfo'
gem 'tzinfo-data'
#gem 'puma'

# gem 'sass-rails', '~> 5.0'
# gem 'uglifier', '>= 1.3.0'
# gem 'coffee-rails', '~> 4.1.0'
# gem 'jquery-rails'
# gem 'jbuilder', '~> 2.0'
# gem 'bootstrap-sass'
# gem 'high_voltage'

group :development do
  gem 'better_errors'
  gem 'html2haml'
  gem 'rails_layout'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  # gem 'spring'
end
